[package]
name = "saturn"
version = "0.0.1"
description = "A modern MIPS IDE."
authors = ["desgroup"]
license = ""
repository = ""
edition = "2021"
rust-version = "1.57"

[build-dependencies]
tauri-build = {version = "1.2", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = {version = "1.2", features = ["api-all"] }

anyhow = "1.0.66"
byteorder = "1.4.3"
num = "0.4.0"
num-derive = "0.3.3"
num-traits = "0.2.15"

[features]
default = [ "custom-protocol" ]
custom-protocol = [ "tauri/custom-protocol" ]
